name: Angular CI

on:
  push:
    branches: [master] # Runs when you push to main
  pull_request:
    branches: [master] # Runs when PR created into main

jobs:
  build:
    runs-on: ubuntu-latest # GitHub provides a Linux machine

    steps:
      # 1️⃣ Download your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Use Node 20 (recommended for Angular 18)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies (faster & reliable)
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Angular
      - name: Build Angular App
        run: npm run build

      # 5️⃣ Run Unit Tests (if you use them)
      # - name: Run Tests
      #   run: npm test -- --watch=false
